Write-Output "BIZAP VALIDATION FRAMEWORK"
Write-Output "This will validate all stages of the Bizap app"
Write-Output ""
Write-Output "Choose an option:"
Write-Output "[1] Full Validation (15-20 min, requires device)"
Write-Output "[2] Quick Validation (5 min, no device needed)"
Write-Output "[3] Exit"
Write-Output ""
$choice = Read-Host "Select option (1/2/3)"
if ($choice -eq "1") {
    Write-Output ""
    Write-Output "Starting full validation..."
    Write-Output ""
    & ".\01_STAGE1_QuickTest.ps1"
    Read-Host "Stage 1 complete. Press Enter to continue to Stage 2"
    & ".\02_STAGE2_BuildAPK.ps1"
    Read-Host "Stage 2 complete. Press Enter to continue to Stage 3"
    & ".\03_STAGE3_CoreFeatures.ps1"
    Read-Host "Stage 3 complete. Install APK and test manually on device. Press Enter when done"
    & ".\04_STAGE4_PDFCustomization.ps1"
    Read-Host "Stage 4 complete. Test PDF customization manually. Press Enter when done"
    & ".\05_STAGE5_LogcatMonitor.ps1"
    Read-Host "Stage 5 complete. Press Enter for final regression test"
    & ".\06_STAGE6_FullBuild.ps1"
    Write-Output ""
    Write-Output "VALIDATION COMPLETE"
}
elseif ($choice -eq "2") {
    Write-Output ""
    Write-Output "Starting quick validation (code quality + build only)..."
    Write-Output ""
    & ".\01_STAGE1_QuickTest.ps1"
    Read-Host "Stage 1 complete. Press Enter for APK build"
    & ".\02_STAGE2_BuildAPK.ps1"
    Read-Host "Stage 2 complete. Press Enter for full regression test"
    & ".\06_STAGE6_FullBuild.ps1"
    Write-Output ""
    Write-Output "QUICK VALIDATION COMPLETE"
}
else {
    Write-Output "Exited."
}
