Write-Output "=========================================="
Write-Output "STAGE 3: CORE FEATURE VALIDATION"
Write-Output "=========================================="
Write-Output ""
Write-Output "Step 1: Checking for connected devices..."
Write-Output ""
$devices = adb devices 2>&1
Write-Output $devices
if ($devices -match "device$") {
    Write-Output ""
    Write-Output "Device Status: CONNECTED"
    Write-Output ""
    Write-Output "Step 2: Installing APK..."
    Write-Output ""
    $apkPath = "app\build\outputs\apk\debug\app-debug.apk"
    $installOutput = adb install -r $apkPath 2>&1
    Write-Output $installOutput
    if ($installOutput -match "Success") {
        Write-Output ""
        Write-Output "Installation Status: SUCCESS"
        Write-Output ""
        Write-Output "Step 3: Launching app..."
        Write-Output ""
        $launchOutput = adb shell am start -n com.emul8r.bizap/.MainActivity 2>&1
        Write-Output $launchOutput
        Write-Output ""
        Write-Output "=========================================="
        Write-Output "MANUAL TESTING REQUIRED"
        Write-Output "=========================================="
        Write-Output ""
        Write-Output "On your device, verify:"
        Write-Output ""
        Write-Output "[ ] SPLASH SCREEN"
        Write-Output "    - Logo appears and animates"
        Write-Output "    - Transitions smoothly to next screen"
        Write-Output ""
        Write-Output "[ ] PIN ENTRY SCREEN"
        Write-Output "    - PIN input visible"
        Write-Output "    - Accept valid PIN"
        Write-Output ""
        Write-Output "[ ] LANDING SCREEN"
        Write-Output "    - Shows 3 GUI options"
        Write-Output "    - Each button clickable"
        Write-Output ""
        Write-Output "[ ] GUI1 (CLASSIC)"
        Write-Output "    - Launches without crash"
        Write-Output "    - Traditional UI visible"
        Write-Output ""
        Write-Output "[ ] GUI2 (MODERN)"
        Write-Output "    - Launches without crash"
        Write-Output "    - Material Design 3 UI visible"
        Write-Output ""
        Write-Output "[ ] GUI3 (MATRIX)"
        Write-Output "    - Launches without crash"
        Write-Output "    - Green cyberpunk theme visible"
        Write-Output "    - Animations smooth"
        Write-Output ""
        Write-Output "[ ] DASHBOARD"
        Write-Output "    - Data loads and displays"
        Write-Output "    - Navigation works"
        Write-Output ""
        Write-Output "=========================================="
        Write-Output ""
        Write-Output "STAGE 3: READY FOR MANUAL TESTING"
        Write-Output "Complete the checklist above on your device"
    } else {
        Write-Output ""
        Write-Output "Installation Status: FAILED"
        Write-Output "Check output above for errors"
    }
} else {
    Write-Output ""
    Write-Output "Device Status: NOT CONNECTED"
    Write-Output ""
    Write-Output "Please:"
    Write-Output "  1. Connect your Android device via USB"
    Write-Output "  2. Enable USB Debugging in Developer Options"
    Write-Output "  3. Run this script again"
}
