package com.emul8r.bizap.domain.model
/**
 * IMMUTABLE SNAPSHOT OF INVOICE AT GENERATION TIME
 * All monetary amounts are stored as Long (cents)
 */
data class InvoiceSnapshot(
    val invoiceId: Long,
    val invoiceNumber: String,
    val displayName: String = "",
    val customerName: String,
    val customerAddress: String,
    val customerEmail: String?,
    val customerPhone: String? = null,
    val date: Long,
    val dueDate: Long,
    val items: List<LineItemSnapshot>,
    val subtotal: Long,
    val taxRate: Double,
    val taxAmount: Long,
    val totalAmount: Long,
    val businessName: String,
    val businessAbn: String,
    val businessEmail: String,
    val businessPhone: String,
    val businessAddress: String,
    val logoBase64: String?,
    val currencyCode: String = "AUD",
    val header: String = "",
    val subheader: String = "",
    val footerText: String = "",
    val notes: String = "",
    val bankAccountName: String = "",
    val bankAccountNumber: String = "",
    val bankBsb: String = "",
    val bankName: String = "",
    val invoiceStatus: String = "DRAFT",
    val taxName: String = "GST",
    val paymentTermsDays: Int = 30,
    val taxHandling: TaxHandling = TaxHandling.EXCLUSIVE,
    val defaultPaymentNotes: String = "",
    val companyWebsite: String = "",
    val alternateRowColor: String = "#FAFAFA",  // Very subtle zebra — not a spreadsheet grid
    val dividerColor: String = "#CCCCCC",
    val dividerThicknessPx: Float = 1f,
    val enableAlternatingRowColors: Boolean = true,
    val enableDividers: Boolean = false,  // Default off — clean table without grid lines
    val isQuote: Boolean = false,
    val primaryColor: String = "#6B4C9A",
    val secondaryColor: String = "#f5f5f5",
    val cornerRadiusDp: Float = 8f,
    val shadowIntensity: Float = 0.15f,
    val highlightTotals: Boolean = true,
    val totalBoxStyle: TotalBoxStyle = TotalBoxStyle.SUBTLE_BACKGROUND,
    val selectedLocale: InvoiceLocale = InvoiceLocale.AUSTRALIAN,
    val selectedTypography: Typography = Typography.MODERN,
    val selectedColorScheme: ColorScheme = ColorScheme.PROFESSIONAL,
    val selectedSpacingProfile: SpacingProfile = SpacingProfile.NORMAL,
    val visualAccentsJson: String = "",
    val enableMotto: Boolean = false,
    val mottoText: String = "",
    val mottoFontSize: Float = 10f,
    val mottoColor: String = "#666666",
    val enableSignatureArea: Boolean = false,
    val signatureLabel: String = "Authorized By:",
    val signatureLineLengthMm: Float = 40f,
    val enableWatermarkText: Boolean = false,
    val watermarkText: String = "",
    val watermarkOpacity: Float = 0.1f,
    val enableStatusBadges: Boolean = true,
    val badgeStyle: BadgeStyle = BadgeStyle.ROUNDED_FILLED,
    val dividerStyle: DividerStyle = DividerStyle.SOLID,
    val enableGradientHeader: Boolean = true,
    val headerGradientEndColor: String = "#1B3260",  // Deep navy depth-fade (not orange clash)
    val enableLogo: Boolean = false,
    val logoUri: String = "",
    val logoWidthMm: Float = 30f,
    val logoHeightMm: Float = 30f,
    val logoPosition: LogoPosition = LogoPosition.TOP_LEFT,
    val enableQrCode: Boolean = false,
    val qrCodeContent: String = "",
    val qrCodeSizeMm: Float = 20f,
    val qrCodePosition: QrCodePosition = QrCodePosition.BOTTOM_RIGHT,
    val enablePaymentIcons: Boolean = false,
    val acceptedPaymentMethodsJson: String = "[]",
    val paymentIconsSize: Float = 16f,
    val enableBackgroundPattern: Boolean = false,
    val backgroundPatternType: BackgroundPattern = BackgroundPattern.WAVES,
    val patternOpacity: Float = 0.08f,
    // BRAND WATERMARK (background logo image, centred at half-page size)
    val enableBrandWatermark: Boolean = true
)
data class LineItemSnapshot(
    val description: String,
    val quantity: Double,
    val unitPrice: Long,
    val total: Long,
    val isDiscount: Boolean = false
)
