package com.emul8r.bizap.domain.usecase

import com.emul8r.bizap.domain.model.Customer
import com.emul8r.bizap.domain.repository.CustomerRepository
import timber.log.Timber
import javax.inject.Inject

/**
 * UseCase for creating a new customer.
 *
 * **Responsibilities:**
 * - Encapsulate customer creation business logic
 * - Validate customer data
 * - Persist customer to repository
 * - Handle errors appropriately
 *
 * **Benefits:**
 * - Testable business logic layer
 * - Reusable across ViewModels
 * - Clear separation of concerns
 * - Single source of truth for validation
 */
class CreateCustomerUseCase @Inject constructor(
    private val customerRepository: CustomerRepository
) {

    /**
     * Create a new customer.
     *
     * @param name Customer name (required)
     * @param businessName Customer business name (optional)
     * @param email Customer email (optional but validated if provided)
     * @param phone Customer phone (optional)
     * @param address Customer address (optional)
     * @param notes Customer notes (optional)
     * @return Result with customer ID on success
     */
    suspend fun execute(
        name: String,
        businessName: String = "",
        email: String = "",
        phone: String = "",
        address: String = "",
        notes: String = ""
    ): Result<Long> {
        return try {
            // Validate name (required)
            if (name.isBlank()) {
                Timber.w("Customer creation validation failed: name is blank")
                return Result.failure(
                    IllegalArgumentException("Customer name is required")
                )
            }

            // Validate email format (if provided)
            if (email.isNotBlank() &&
                (!email.contains("@") || !email.contains("."))) {
                Timber.w("Customer creation validation failed: invalid email format")
                return Result.failure(
                    IllegalArgumentException("Invalid email format")
                )
            }

            // Create customer entity
            val customer = Customer(
                id = 0,  // ID generated by database
                name = name,
                businessName = businessName,
                email = email,
                phone = phone,
                address = address,
                notes = notes
            )

            Timber.d("Creating customer: name=$name, email=$email")

            // Save to repository
            val result = customerRepository.insert(customer)

            result.onSuccess { id ->
                Timber.i("✅ Customer created successfully with ID: $id")
            }.onFailure { error ->
                Timber.e(error, "❌ Failed to create customer")
            }

            result
        } catch (e: Exception) {
            Timber.e(e, "❌ Unexpected error creating customer")
            Result.failure(e)
        }
    }
}

