name: Bizap CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x Bizap/gradlew

    - name: Build with Gradle
      run: cd Bizap && ./gradlew assembleDebug

    - name: Run Unit Tests
      run: cd Bizap && ./gradlew testDebugUnitTest

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: Bizap/app/build/reports/tests/testDebugUnitTest/
